include:
  - path: ./compose/observability.yaml
    project_directory: .
    env_file: .env

  - path: ./compose/compute.yaml
    project_directory: .
    env_file: .env

networks:
  private:
    driver: bridge
    name: dw_intel_private
  public:
    driver: bridge
    name: dw_intel_public