openapi: 3.0.0
info:
  title: Cashflow DataMap Schema API
  description: |
    Cashflow DataMap Schema API helps you analyze and query database schema using AWS Bedrock and RAG.

    ## Features
    * Natural language querying of database schema
    * Similarity-based schema retrieval
    * Table and column-level schema analysis
    * Interactive API documentation
    * S3-based data source with parquet files
    * ERD (Entity Relationship Diagram) generation and visualization
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:8000/api/v1
    description: Local development server

tags:
  - name: root
    description: Basic API information and health check
  - name: analysis
    description: Schema analysis and operations
  - name: tables
    description: Table-specific operations and schema
  - name: columns
    description: Column-specific operations and analysis
  - name: execute_sql
    description: SQL query execution operations

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  headers:
    X-Request-ID:
      description: Unique request identifier
      schema:
        type: string
    X-RateLimit-Limit:
      description: The maximum number of requests per minute
      schema:
        type: integer
    X-RateLimit-Remaining:
      description: The number of requests remaining in the current rate limit window
      schema:
        type: integer
    X-RateLimit-Reset:
      description: The time at which the current rate limit window resets
      schema:
        type: integer

  parameters:
    page:
      name: page
      in: query
      description: Page number
      required: false
      schema:
        type: integer
        default: 1
    page_size:
      name: page_size
      in: query
      description: Number of items per page
      required: false
      schema:
        type: integer
        default: 10
        maximum: 100
    context:
      name: context
      in: query
      description: Context for the query
      required: false
      schema:
        type: string
        default: "cashflow"
    format_type:
      name: format_type
      in: query
      description: Format type for the response
      required: false
      schema:
        type: string
        default: "sql"

  schemas:
    QueryRequest:
      type: object
      required:
        - query
      properties:
        query:
          type: string
          description: Natural language query about the database schema
        k:
          type: integer
          description: Number of results to return
          minimum: 1
          maximum: 10
          default: 3
        context:
          type: string
          description: Context for the query (e.g., "cashflow")
          default: "cashflow"
        format_type:
          type: string
          description: Format type for the response (e.g., "sql")
          default: "sql"

    SQLRequest:
      type: object
      required:
        - sql
      properties:
        sql:
          type: string
          description: SQL query to execute

    SQLResponse:
      type: object
      required:
        - results
      properties:
        results:
          type: array
          items:
            type: object
          description: Query results

    TableRequest:
      type: object
      required:
        - table_name
      properties:
        table_name:
          type: string
          description: Name of the table to get schema for

    ColumnRequest:
      type: object
      required:
        - table_name
        - column_name
      properties:
        table_name:
          type: string
          description: Name of the table
        column_name:
          type: string
          description: Name of the column

    ConfigRequest:
      type: object
      required:
        - config
      properties:
        config:
          type: object
          description: Configuration data for the analyzer
          properties:
            bucket_name:
              type: string
              description: S3 bucket name
            prefix:
              type: string
              description: S3 prefix
            region_name:
              type: string
              description: AWS region name
            cache_size:
              type: integer
              description: Cache size for RAG
            pattern:
              type: string
              description: File pattern for schema files

    AnalysisResponse:
      type: object
      required:
        - analysis
        - query
      properties:
        analysis:
          type: string
          description: Analysis results
        query:
          type: string
          description: Original query

    SimilarResponse:
      type: object
      required:
        - similar_schema
        - scores
      properties:
        similar_schema:
          type: array
          items:
            type: string
          description: List of similar schema entries
        scores:
          type: array
          items:
            type: number
          description: Similarity scores for each entry

    TableResponse:
      type: object
      required:
        - name
        - columns
        - row_count
        - last_modified
        - size_bytes
        - column_count
      properties:
        name:
          type: string
          description: Table name
        columns:
          type: array
          items:
            type: object
          description: Table columns schema
        column_count:
          type: integer
          description: Number of columns in the table
        row_count:
          type: integer
          description: Number of rows in the table
        last_modified:
          type: string
          description: Last modified timestamp
        size_bytes:
          type: integer
          description: File size in bytes

    ColumnResponse:
      type: object
      required:
        - name
        - type
        - nullable
        - unique_values
        - null_count
        - sample_values
      properties:
        name:
          type: string
          description: Column name
        type:
          type: string
          description: Column data type
        nullable:
          type: boolean
          description: Whether column contains nulls
        unique_values:
          type: integer
          description: Number of unique values
        null_count:
          type: integer
          description: Number of null values
        sample_values:
          type: array
          items:
            type: any
          description: Sample of unique values

    SchemaSummaryResponse:
      type: object
      required:
        - total_tables
        - tables
      properties:
        total_tables:
          type: integer
          description: Total number of tables
        tables:
          type: array
          items:
            type: object
            required:
              - name
              - column_count
              - columns
              - row_count
              - last_modified
              - size_bytes
            properties:
              name:
                type: string
                description: Table name
              column_count:
                type: integer
                description: Number of columns in the table
              columns:
                type: array
                items:
                  type: string
                description: List of column names
              row_count:
                type: integer
                description: Number of rows in the table
              last_modified:
                type: string
                description: Last modified timestamp
              size_bytes:
                type: integer
                description: File size in bytes

    ErrorResponse:
      type: object
      required:
        - detail
        - status_code
        - error_type
      properties:
        detail:
          type: string
          description: Error message
        status_code:
          type: integer
          description: HTTP status code
        error_type:
          type: string
          description: Type of error

    SQLInContextResponse:
      type: object
      required:
        - sql_in_context
        - query
        - validation_status
        - validation_message
      properties:
        sql_in_context:
          type: string
          description: SQL query in context
        query:
          type: string
          description: Original query
        validation_status:
          type: string
          description: Status of SQL validation (success/failed)
          enum:
            - success
            - failed
        validation_message:
          type: string
          description: Detailed message about the validation result

    ERDRequest:
      type: object
      required:
        - query
      properties:
        query:
          type: string
          description: Query to analyze for ERD generation
        context:
          type: string
          description: Context for the query
          default: "database_schema"
        format_type:
          type: string
          description: Format type for the response
          default: "json"

    ERDResponse:
      type: object
      required:
        - enriched_schema
        - erd_files
        - query
        - context
        - format_type
      properties:
        enriched_schema:
          type: object
          description: Detailed schema analysis results
        erd_files:
          type: object
          description: Dictionary containing paths to generated ERD files (svg, png, json)
          properties:
            svg:
              type: string
              description: Path to SVG file
            png:
              type: string
              description: Path to PNG file
            json:
              type: string
              description: Path to JSON file
        query:
          type: string
          description: Original query used for analysis
        context:
          type: string
          description: Context used for analysis
        format_type:
          type: string
          description: Format type used for analysis

    ERDFilesResponse:
      type: object
      required:
        - json
      properties:
        svg:
          type: string
          nullable: true
          description: Path to latest SVG file (null if not generated)
        png:
          type: string
          nullable: true
          description: Path to latest PNG file (null if not generated)
        json:
          type: string
          description: Path to latest JSON file

  examples:
    AnalysisResponseExample:
      value:
        analysis: "The schema contains 5 tables with relationships between them..."
        query: "What are the main tables in the schema?"
    ErrorResponseExample:
      value:
        detail: "Analyzer not initialized"
        status_code: 500
        error_type: "InitializationError"

paths:
  /:
    get:
      tags:
        - root
      summary: Root endpoint
      description: Returns API status
      responses:
        '200':
          description: API status
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Cashflow DataMap Schema API"

  /initialize:
    post:
      tags:
        - root
      summary: Initialize analyzer
      description: Initialize the analyzer with provided configuration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfigRequest'
      responses:
        '200':
          description: Analyzer initialized successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Analyzer initialized successfully"
        '500':
          description: Error initializing analyzer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /analyze:
    post:
      tags:
        - analysis
      summary: Analyze schema
      description: Analyze database schema based on natural language query
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
      responses:
        '200':
          description: Analysis results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalysisResponse'
        '500':
          description: Error processing query
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /similar:
    post:
      tags:
        - analysis
      summary: Get similar schema
      description: Get similar schema entries with similarity scores
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
      responses:
        '200':
          description: Similar schema entries
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimilarResponse'
        '500':
          description: Error getting similar schema
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /table:
    post:
      tags:
        - tables
      summary: Get table schema
      description: Get detailed schema information about a specific table
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TableRequest'
      responses:
        '200':
          description: Table schema information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TableResponse'
        '500':
          description: Error getting table schema
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /column:
    post:
      tags:
        - columns
      summary: Get column info
      description: Get detailed information about a specific column
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ColumnRequest'
      responses:
        '200':
          description: Column information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ColumnResponse'
        '500':
          description: Error getting column info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /schema:
    get:
      tags:
        - analysis
      summary: Get schema summary
      description: Get summary of entire database schema
      responses:
        '200':
          description: Schema summary
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SchemaSummaryResponse'
        '500':
          description: Error getting schema summary
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /sql_in_context:
    post:
      tags:
        - analysis
      summary: Get SQL in context
      description: Get SQL query in context based on natural language query
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
      responses:
        '200':
          description: SQL in context
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SQLInContextResponse'
        '500':
          description: Error processing query
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /sql_in_context_v2:
    post:
      tags:
        - analysis
      summary: Get enhanced SQL in context
      description: Get SQL query in context using enhanced document-based embeddings with better context understanding
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
      responses:
        '200':
          description: Enhanced SQL in context
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SQLInContextResponse'
        '500':
          description: Error processing query
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /execute_sql:
    post:
      tags:
        - execute_sql
      summary: Execute SQL query
      description: Execute a SQL query via duckdb to the S3 bucket in the configuration prefix and pattern
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SQLRequest'
      responses:
        '200':
          description: SQL execution results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SQLResponse'
        '500':
          description: Error executing SQL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /generate_erd/analyze:
    post:
      tags:
        - analysis
      summary: Generate ERD
      description: Analyze schema and generate Entity Relationship Diagram (ERD) based on the provided query
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ERDRequest'
      responses:
        '200':
          description: ERD generation results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERDResponse'
        '500':
          description: Error generating ERD
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /generate_erd/files:
    get:
      tags:
        - analysis
      summary: Get latest ERD files
      description: Get paths to the latest generated ERD files
      responses:
        '200':
          description: Latest ERD files
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERDFilesResponse'
        '500':
          description: Error getting ERD files
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse' 