services:
  api:
    build:
      context: ./src
      dockerfile: Dockerfile
      args:
        - BASE_DIR=quack
        - PROJECT_NAME=datamap_api
        - PROJECT_DIR=datamap_api
    container_name: quack-api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
      - "$HOME/.aws:/root/.aws" # Mount the AWS credentials file
      - /app/.venv # Ignore the virtual environment
      - ./src/hydration_data:/app/hydration_data # Mount the hydration data
    env_file:
      - .env
    entrypoint: ["sh", "-c", "python3 -m quack.datamap_api"]

  ui:
    build:
      context: ./src
      dockerfile: Dockerfile
      args:
        - BASE_DIR=quack
        - PROJECT_NAME=datamap_streamlit
        - PROJECT_DIR=datamap_streamlit
    container_name: quack-ui
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app
      - "$HOME/.aws:/root/.aws" # Mount the AWS credentials file
      - /app/.venv # Ignore the virtual environment
      - ./src/hydration_data:/app/hydration_data # Mount the hydration data
    env_file:
      - .env
    entrypoint:
      [
        "sh",
        "-c",
        "python -m streamlit run quack/datamap_streamlit/ui.py",
      ]
